// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSKYtZ-25slNnM106phcdpxX6vrDcA9q8',
    appId: '1:190008956966:web:eb9b04c485277cf4ca2ee7',
    messagingSenderId: '190008956966',
    projectId: 'chat-flash-434b9',
    authDomain: 'chat-flash-434b9.firebaseapp.com',
    storageBucket: 'chat-flash-434b9.appspot.com',
    measurementId: 'G-LVJY6VXSFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1KN-q54jTfSrN6DGaGHld2nPw4QOBu3M',
    appId: '1:190008956966:android:795b269582589b5bca2ee7',
    messagingSenderId: '190008956966',
    projectId: 'chat-flash-434b9',
    storageBucket: 'chat-flash-434b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcFUZ-bh05eeIVIKCP1VwKJPpW73A0mjs',
    appId: '1:190008956966:ios:2268c31249ebb757ca2ee7',
    messagingSenderId: '190008956966',
    projectId: 'chat-flash-434b9',
    storageBucket: 'chat-flash-434b9.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcFUZ-bh05eeIVIKCP1VwKJPpW73A0mjs',
    appId: '1:190008956966:ios:1e285bfc89a3a455ca2ee7',
    messagingSenderId: '190008956966',
    projectId: 'chat-flash-434b9',
    storageBucket: 'chat-flash-434b9.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
